export { GambaModalButton } from './GambaModalButton'
export { GambaUiProvider, GambaUi } from './Provider'
export { GambaLogo } from './Svg'
export { Button } from './components/Button'
export { GameWrapper, Wrapper as StyledGameWrapper } from './components/GameWrapper'
export { Modal } from './components/Modal'
export { ResponsiveSize } from './components/ResponsiveSize'
export { RecentPlays } from './components/RecentPlays'
export { ErrorBoundary } from './components/ErrorBoundary'
export { ActionBar } from './styles'
export { useGambaUi } from './context'
export * from './types'
